### ISSUE TITLE
Add tty option to copier.yaml

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/hyperfast-docker-template#218]
## Description

Currently, the `hyperfast-docker-template` copier.yaml does not have an option to enable or disable the tty (pseudo-terminal) when running the Docker container. This can be useful for certain applications that require interactive input or output.

## Proposed Changes

1. Add a new configuration option `use_tty` to the `copier.yaml` file:

```yaml
use_tty:
  default: false
  type: bool
  help: Do you want to enable tty (pseudo-terminal) when running the Docker container?
```

2. Update the relevant documentation and examples to reflect the new use_tty option..

## Benefits

Adding a tty option to the copier.yaml will provide users with more flexibility when running their Docker containers. It will allow them to enable or disable the pseudo-terminal based on their application's requirements, improving the overall user experience.

## Drawbacks

There are no significant drawbacks to adding this option. However, it will require modifying the existing template files and updating the documentation.

## Alternatives

An alternative approach would be to always enable the tty option by default, but this may not be desirable for all use cases.

## Testing

The new use_tty option should be thoroughly tested with various applications and scenarios to ensure it works as expected.

## Tasks

- [ ] Add use_tty option to copier.yaml
- [ ] Update docker-compose.base.yaml.jinja to include tty option
- [ ] Update documentation and examples
- [ ] Test the new use_tty option with different applications and scenarios

## References

Docker Compose tty option
Docker run tty option
