### ISSUE TITLE
Add conditional questions and docker-compose-only support 

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/hyperfast-docker-template#32]
## Description

This issue adds two new features to `copier.yaml`:

1. Support for conditional questions where later questions depend on the answers to previous questions.

2. Allow generating a `docker-compose.yaml` without Dockerfiles for cases that don't need custom images.

## Tasks

- [ ] Update `copier.yaml` schema to support `if` conditionals on questions

- [ ] Add example conditional questions:

  - Only ask for `custom_image` if `use_custom_image` is true

  - Only ask for `dockerfile` path if `custom_image` is set

- [x] Add new `docker_compose_only` question 
  
- [x] Update Dockerfile generation to be skipped if `docker_compose_only` is true

- [ ] Update README docs with new configuration options

## Acceptance Criteria

- Conditional questions work correctly based on previous answers

- Can generate `docker-compose.yaml` without Dockerfiles

- README updated with documentation on new configuration

- Existing functionality not broken

https://github.com/entelecheia/hyperfast-docker-template/blob/52d87158b2fe8b3ea6d648ca770fe811f4f67be8/copier.yaml#L102-L250
